#!/usr/bin/env python3

import math
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
PKG_PATH = ROOT / "rtl" / "croc_pkg.sv"
TB_PKG_PATH = ROOT / "rtl" / "test" / "tb_croc_pkg.sv"
CHIP_PATH = ROOT / "rtl" / "croc_chip.sv"
USER_PKG_PATH = ROOT / "rtl" / "user_pkg.sv"
OUT_PATH = ROOT / "sw" / "config.h"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def extract(pattern: str, text: str, path: Path) -> str:
    match = re.search(pattern, text, re.MULTILINE)
    if not match:
        raise SystemExit(f"error: could not match {pattern!r} in {path}")
    return match.group(1)


def sv_int(value: str) -> int:
    value = value.strip()

    sized_match = re.fullmatch(r"(?:\d+)'([hdob])([0-9a-fA-F_xzXZ]+)", value)
    if sized_match:
        base = {"h": 16, "d": 10, "o": 8, "b": 2}[sized_match.group(1).lower()]
        digits = sized_match.group(2).replace("_", "")
        return int(digits, base)

    plain = value.replace("_", "")
    if plain.startswith("0x") or plain.startswith("0X"):
        return int(plain, 16)
    return int(plain, 10)


def hex32(value: int) -> str:
    return f"0x{value:08X}"


pkg_text = read_text(PKG_PATH)
tb_pkg_text = read_text(TB_PKG_PATH)
chip_text = read_text(CHIP_PATH)
user_pkg_text = read_text(USER_PKG_PATH)

periph_entries = dict(
    re.findall(
        r"'\{\s*idx:\s*(Periph\w+),\s*start_addr:\s*(32'h[0-9A-Fa-f_]+),",
        pkg_text,
        re.MULTILINE,
    )
)

user_base = sv_int(
    extract(
        r"'\{\s*idx:\s*XbarUser,\s*start_addr:\s*(32'h[0-9A-Fa-f_]+),",
        pkg_text,
        PKG_PATH,
    )
)
fft_offset = sv_int(
    extract(
        r"start_addr:\s*croc_pkg::UserBaseAddr\s*\+\s*(32'h[0-9A-Fa-f_]+)",
        user_pkg_text,
        USER_PKG_PATH,
    )
)

fft_length = sv_int(extract(r"parameter\s+int\s+unsigned\s+FftLength\s*=\s*([^,\n]+)", chip_text, CHIP_PATH))
fft_data_width = sv_int(extract(r"parameter\s+int\s+unsigned\s+FftDataWidth\s*=\s*([^,\n]+)", chip_text, CHIP_PATH))
tb_frequency = sv_int(extract(r"ClkPeriodSys\s*=\s*(\d+)ns", tb_pkg_text, TB_PKG_PATH))
tb_baudrate = sv_int(extract(r"UartBaudRate\s*=\s*(\d+)", tb_pkg_text, TB_PKG_PATH))

if fft_length <= 0 or (fft_length & (fft_length - 1)) != 0:
    raise SystemExit(f"error: FftLength must be a positive power of two, got {fft_length}")

tb_frequency_hz = 1_000_000_000 // tb_frequency
fft_log2_length = int(math.log2(fft_length))

output = f"""// Copyright 2022 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Nils Wistoff <nwistoff@iis.ee.ethz.ch>
// Paul Scheffler <paulsc@iis.ee.ethz.ch>
//
// This file is generated by scripts/generate_sw_config.py from rtl/croc_pkg.sv,
// rtl/user_pkg.sv, rtl/test/tb_croc_pkg.sv, and rtl/croc_chip.sv.

#pragma once

// Address map
#define DEBUG_BASE_ADDR     {hex32(sv_int(periph_entries['PeriphDebug']))}
#define BOOTROM_BASE_ADDR   {hex32(sv_int(periph_entries['PeriphBootrom']))}
#define CLINT_BASE_ADDR     {hex32(sv_int(periph_entries['PeriphClint']))}
#define SOCCTRL_BASE_ADDR   {hex32(sv_int(periph_entries['PeriphSocCtrl']))}
#define UART_BASE_ADDR      {hex32(sv_int(periph_entries['PeriphUart']))}
#define GPIO_BASE_ADDR      {hex32(sv_int(periph_entries['PeriphGpio']))}
#define OBI_TIMER_BASE_ADDR {hex32(sv_int(periph_entries['PeriphTimer']))}
#define IDMA_BASE_ADDR      {hex32(sv_int(periph_entries['PeriphiDMA']))}
#define USER_ROM_BASE_ADDR  {hex32(user_base)}
#define FFT_BASE_ADDR       {hex32(user_base + fft_offset)}

// Frequencies
#define TB_FREQUENCY        {tb_frequency_hz}
#define TB_BAUDRATE         {tb_baudrate}

// Peripheral configs
// UART
#define UART_BYTE_ALIGN     4
#define UART_FREQ           TB_FREQUENCY
#define UART_BAUD           TB_BAUDRATE

// FFT synthesized configuration expected by software tests and buffers.
// Override these at compile time (for example with -DFFT_SYNTH_LENGTH=8)
// when simulating a non-default FFT build.
#ifndef FFT_SYNTH_LENGTH
#define FFT_SYNTH_LENGTH {fft_length}
#endif

#ifndef FFT_SYNTH_LOG2_LENGTH
#define FFT_SYNTH_LOG2_LENGTH {fft_log2_length}
#endif

#ifndef FFT_SYNTH_DATA_WIDTH
#define FFT_SYNTH_DATA_WIDTH {fft_data_width}
#endif

// Interrupts
#define IRQ_SOFTWARE  3
#define IRQ_TIMER     7
#define IRQ_EXTERNAL  11
#define IRQ_OBI_TIMER 16
#define IRQ_UART      17
#define IRQ_GPIO      18
#define IRQ_IDMA      19
#define IRQ_FFT       20
"""

OUT_PATH.write_text(output, encoding="utf-8")